services:
  - type: web
    name: portail-mairie-douala-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
